### ISSUE TITLE
Steps files location

### ISSUE THREAD

**Issue by michelts** [koterpillar/aloe#60] opened 2015-10-02 12:45 UTC
Hi @koterpillar 

Now the #53 is done (what I mistakenly called "Steps files locaiton", but talked about features files location), I wan't to clarify the steps files location.

You tell:

> Steps can and should be defined in separate modules to the main application code. Aloe searches for modules to load steps from inside the features directories.

This way, I suppose the steps file in the example should be found?

```
my_tests/
    __init__.py
    sample_app/
        __init__.py
        features/
            __init__.py
            sample.feature
            steps.py
```

Do I need to import anything in the `__init__.py` files?

When I run it, I got the following error:

```
$ cd my_tests/
$ aloe
Traceback (most recent call last):
  File "/home/michel/.virtualenvs/aloe/bin/aloe", line 9, in <module>
    load_entry_point('aloe==0.0.26', 'console_scripts', 'aloe')()
  File "/home/michel/.virtualenvs/aloe/src/myaloe/aloe/__init__.py", line 36, in main
    Runner(argv)
  File "/home/michel/.virtualenvs/aloe/src/myaloe/aloe/runner.py", line 48, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/dist-packages/nose/core.py", line 145, in parseArgs
    self.config.configure(argv, doc=self.usage())
  File "/usr/lib/python2.7/dist-packages/nose/config.py", line 347, in configure
    self.plugins.begin()
  File "/usr/lib/python2.7/dist-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/usr/lib/python2.7/dist-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/home/michel/.virtualenvs/aloe/src/myaloe/aloe/plugin.py", line 65, in begin
    FeatureLoader.find_and_load_step_definitions(feature_dir)
  File "/home/michel/.virtualenvs/aloe/src/myaloe/aloe/fs.py", line 60, in find_and_load_step_definitions
    module = import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named sample_app.features.steps
```

**Comment by koterpillar** [comment] 2015-10-02 13:08
You don't seem to have `my_tests/__init__.py`, so neither the feature nor the steps should be found. Fixed in #61.

**Comment by michelts** [comment] 2015-10-02 13:10
I forgot to put the `my_tests/__init__.py` in the issue description, but it is here.

I tried #61 branch and I got the same error. By the way, I'm using python 2.7.

**Comment by koterpillar** [comment] 2015-10-02 13:22
Can you import `sample_app.features.steps` yourself? I.e.

```
$ cd my_tests/
$ python
>>> import sample_app.features.steps
```

**Comment by michelts** [comment] 2015-10-02 13:22
Yes, I can.

I changed the code to highlight the PATH just before import_module:

```
def find_and_load_step_definitions(cls, dir_):
    ...
    import sys
    for path in sys.path:
        print('\t', path)
    module = import_module(module_name)
    reload(module)  # Make sure steps and hooks are registered
```

It seems the root package isn't in the path for some reason.

**Comment by koterpillar** [comment] 2015-10-02 13:24
Aloe doesn't modify `sys.path` except for testing. If you print `sys.path` instead of printing entries one by one, do you see an empty one at the start, signifying the current directory?

**Comment by michelts** [comment] 2015-10-02 13:28
No, but If I add '.' to sys.path in aloe/plugin.py, near line 60, it works:

```
    def begin(self):
        ...
        import sys
        sys.path.append('.')
        self.feature_dirs = [
            dir_
            for dir_ in FeatureLoader.find_feature_directories('.')
        ]
```

**Comment by koterpillar** [comment] 2015-10-02 13:29
Curious, can you please do:

```
$ cd my_tests/
$ python
>>> import sys
>>> print sys.path
>>> import sample_app.features.steps
```

**Comment by michelts** [comment] 2015-10-02 13:34
It works:

```
>>> import sys
>>> print sys.path
['', '/home/michel/.virtualenvs/aloe/src/myaloe', '/home/michel/.virtualenvs/aloe/lib/python2.7', '/home/michel/.virtualenvs/aloe/lib/python2.7/plat-x86_64-linux-gnu', '/home/michel/.virtualenvs/aloe/lib/python2.7/lib-tk', '/home/michel/.virtualenvs/aloe/lib/python2.7/lib-old', '/home/michel/.virtualenvs/aloe/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/home/michel/.virtualenvs/aloe/local/lib/python2.7/site-packages', '/home/michel/.virtualenvs/aloe/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/ubuntuone-client', '/usr/lib/python2.7/dist-packages/ubuntuone-couch', '/usr/lib/python2.7/dist-packages/ubuntuone-storage-protocol']
>>> import sample_app.features.steps
>>> 
```

But inside a aloe session, without the fix I told:

```
['/home/michel/.virtualenvs/aloe/bin', '/home/michel/.virtualenvs/aloe/src/myaloe', '/home/michel/.virtualenvs/aloe/lib/python2.7', '/home/michel/.virtualenvs/aloe/lib/python2.7/plat-x86_64-linux-gnu', '/home/michel/.virtualenvs/aloe/lib/python2.7/lib-tk', '/home/michel/.virtualenvs/aloe/lib/python2.7/lib-old', '/home/michel/.virtualenvs/aloe/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/home/michel/.virtualenvs/aloe/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/ubuntuone-client', '/usr/lib/python2.7/dist-packages/ubuntuone-couch', '/usr/lib/python2.7/dist-packages/ubuntuone-storage-protocol']
```

**Comment by koterpillar** [comment] 2015-10-02 13:47
Reproduced here. The difference is because `aloe` script resides in `/home/michel/.virtualenvs/aloe/bin` so it and not the current directory is added to the path.

I'll look at what Nose does and try to replicate that for Aloe.

**Comment by michelts** [comment] 2015-10-02 13:51
Thanks!

**Comment by koterpillar** [comment] 2015-10-03 01:03
Updated #61.

**Closed as completed** 2015-10-08 06:27 UTC
